#!/bin/sh

# automount tftp server based on $eth0.serverip

mkdir -p /mnt/tftp
automount /mnt/tftp 'test -n $global.net.server && mount -t tftp $global.net.server /mnt/tftp'

mkdir -p /mnt/mmc
automount -d /mnt/mmc 'mmc0.probe=1 && [ -e /dev/mmc0.0 ] && mount /dev/mmc0.0 /mnt/mmc'

mkdir -p /mnt/nfs
automount /mnt/nfs 'test -n $global.net.server && mount -t nfs $global.net.server:/srv/nfs /mnt/nfs'
