#!/bin/sh

if [ -n "$nv.boot.default" ]; then
	exit
fi

if [ $bootsource = mmc ]; then
	if [ $bootsource_instance = 0 ]; then
		# MMC
		global.boot.default="mmc nand spi net"
	elif [ $bootsource_instance = 1 ]; then
		# eMMC
		global.boot.default="bootchooser emmc nand spi net"
	fi
elif [ $bootsource = nand ]; then
	global.boot.default="bootchooser nand spi mmc net"
elif [ $bootsource = spi-nor ]; then
	global.boot.default="spi nand mmc net"
elif [ $bootsource = net ]; then
	global.boot.default="net nand spi mmc"
fi
