#!/bin/sh
# KLS custom network boot for automatic network deployment
# The following variables are set from the DHCP request:
# global.dhcp.bootfile
# global.dhcp.oftree_file
# global.dhcp.rootpath
# global.dhcp.tftp_server_name
# global.hostname

# Network/DHCP must be up
ifup eth0
# TODO usb, ifup -a
if test $? -ne 0; then
    usb
    ifup eth1
fi

# Note: /mnt/nfs is mounted by barebox automount
global.bootm.image=$global.dhcp.bootfile
global.bootm.oftree=$global.dhcp.oftree_file

# root=/dev/nfs tells the kernel to use NFS as root file system, requires further parameter "nfsroot"
# nfsroot=<path> path to the root file system in NFS notation [server]:[path_on_server]
# v3,tcp NFS protocol and transport to use
global.linux.bootargs.dyn.root="root=/dev/nfs nfsroot=${global.dhcp.rootpath},v3,tcp"

# Tell kernel to use DHCP
global.linux.bootargs.dyn.ip="ip=dhcp"

# Override default options for internal boot, TODO correct settings
# noati
global.linux.bootargs.rootfs=""
